/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.utp.integrador.view;

import com.utp.integrador.controller.AcercaDeController;
import com.utp.integrador.controller.LoginController;
import com.utp.integrador.controller.MonedaController;
import com.utp.integrador.controller.PaisController;
import com.utp.integrador.controller.TransaccionController;
import com.utp.integrador.controller.UsuarioController;

/**
 *
 * @author Usuario
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Menu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_dni = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        men_sistema = new javax.swing.JMenu();
        men_logout = new javax.swing.JMenuItem();
        men_exit = new javax.swing.JMenuItem();
        menu_registrar = new javax.swing.JMenu();
        men_transaccion = new javax.swing.JMenuItem();
        men_mantenimiento = new javax.swing.JMenu();
        men_usuario = new javax.swing.JMenuItem();
        men_moneda = new javax.swing.JMenuItem();
        men_pais = new javax.swing.JMenuItem();
        men_acerca = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIENVENIDO AL SISTEMA");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_menu.jpg"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("DNI Usuario :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Usuario :");

        men_sistema.setText("Sistema |");

        men_logout.setText("Logout");
        men_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_logoutActionPerformed(evt);
            }
        });
        men_sistema.add(men_logout);

        men_exit.setText("Exit");
        men_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_exitActionPerformed(evt);
            }
        });
        men_sistema.add(men_exit);

        jMenuBar1.add(men_sistema);

        menu_registrar.setText("Registrar |");

        men_transaccion.setText("Transacción");
        men_transaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_transaccionActionPerformed(evt);
            }
        });
        menu_registrar.add(men_transaccion);

        jMenuBar1.add(menu_registrar);

        men_mantenimiento.setText("Mantenimiento  |");

        men_usuario.setText("Usuario");
        men_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_usuarioActionPerformed(evt);
            }
        });
        men_mantenimiento.add(men_usuario);

        men_moneda.setText("Moneda");
        men_moneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_monedaActionPerformed(evt);
            }
        });
        men_mantenimiento.add(men_moneda);

        men_pais.setText("Pais");
        men_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                men_paisActionPerformed(evt);
            }
        });
        men_mantenimiento.add(men_pais);

        jMenuBar1.add(men_mantenimiento);

        men_acerca.setText("Acerca del Sistema");
        men_acerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                men_acercaMouseClicked(evt);
            }
        });
        jMenuBar1.add(men_acerca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_dni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void men_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_logoutActionPerformed
        this.dispose();
        LoginController.callFrmLogin();
    }//GEN-LAST:event_men_logoutActionPerformed

    private void men_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_exitActionPerformed
        dispose();
    }//GEN-LAST:event_men_exitActionPerformed

    private void men_monedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_monedaActionPerformed
        MonedaController.callJDMoneda();
    }//GEN-LAST:event_men_monedaActionPerformed

    private void men_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_usuarioActionPerformed
        UsuarioController.callJDUsuario(lbl_dni.getText());
    }//GEN-LAST:event_men_usuarioActionPerformed

    private void men_transaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_transaccionActionPerformed
        TransaccionController.callJDTransaccion(lbl_dni.getText(), lbl_usuario.getText());
    }//GEN-LAST:event_men_transaccionActionPerformed

    private void men_acercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_men_acercaMouseClicked
        AcercaDeController.callAcerdaDe();
    }//GEN-LAST:event_men_acercaMouseClicked

    private void men_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_men_paisActionPerformed
        PaisController.callJDPais();
    }//GEN-LAST:event_men_paisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JLabel lbl_dni;
    public javax.swing.JLabel lbl_usuario;
    private javax.swing.JMenu men_acerca;
    private javax.swing.JMenuItem men_exit;
    private javax.swing.JMenuItem men_logout;
    public javax.swing.JMenu men_mantenimiento;
    private javax.swing.JMenuItem men_moneda;
    private javax.swing.JMenuItem men_pais;
    private javax.swing.JMenu men_sistema;
    private javax.swing.JMenuItem men_transaccion;
    private javax.swing.JMenuItem men_usuario;
    public javax.swing.JMenu menu_registrar;
    // End of variables declaration//GEN-END:variables
}
