package com.utp.integrador.view;

import com.utp.integrador.controller.CuentaBancariaController;
import com.utp.integrador.controller.TransaccionController;
import com.utp.integrador.model.CuentaBancaria;
import com.utp.integrador.model.Moneda;
import com.utp.integrador.model.Transaccion;
import com.utp.integrador.model.Usuario;
import com.utp.integrador.model.dao.CuentaBancariaDao;
import com.utp.integrador.model.dao.MonedaDao;
import com.utp.integrador.model.dao.UsuarioDao;
import com.utp.integrador.model.dao.impl.CuentaBancariaDaoImp;
import com.utp.integrador.model.dao.impl.MonedaDaoImp;
import com.utp.integrador.model.dao.impl.UsuarioDaoImp;
import com.utp.integrador.utilitarios.Util;
import java.math.BigDecimal;
import java.util.List;

/**
 *
 * @author Usuario
 */
public class JDTransaccion extends javax.swing.JDialog {

    /**
     * Creates new form JD_Transaccion
     */
    MonedaDao monedaDao = new MonedaDaoImp();
    
    public JDTransaccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Util util = new Util(lbl_fechaHora);
        util.start();
        btn_cuenta1.setEnabled(true);
        txt_origenCambio.setText("0.27");
//        txt_origenCambioSoles.setText("3.71");
        generateCod();
        cargarComboMoneda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    void limpiar() {
        generateCod();
        txt_idCuentaBancaria1.setText("");
        txt_idCuentaBancaria2.setText("");
        txt_montoInicial.setText("");
        txt_montoFinal.setText("");
        lbl_simboloOrign.setText("");
        txt_accountOrigen.setText("");
        cbox_tipoMoneda.setSelectedIndex(0);
//        txt_montoInicialDolares.setText("");
//        txt_montoFinalSoles.setText("");
        lbl_simboloDestiny.setText("");
        txt_accountDestino.setText("");
        
    }
    
    void generateCod() {
        lbl_IDTransaccion.setText(String.valueOf(Util.generateUniqueId()));
    }
    
    void cargarComboMoneda() {
        
        List<Moneda> nombreMonedaList = monedaDao.getLastDistinctNombreMoneda();
        for (Moneda moneda : nombreMonedaList) {
            cbox_tipoMoneda.addItem(moneda.getNombre());
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbl_user = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_simboloOrigen = new javax.swing.JLabel();
        txt_origenCambio = new javax.swing.JTextField();
        lbl_simboloCambio = new javax.swing.JLabel();
        txt_montoInicial = new javax.swing.JTextField();
        lbl_simboloDestino = new javax.swing.JLabel();
        txt_montoFinal = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jRadioBtn_transferencia = new javax.swing.JRadioButton();
        jRadioBtn_retiro = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        lbl_dni = new javax.swing.JLabel();
        lbl_IDTransaccion = new javax.swing.JLabel();
        lbl_fechaHora = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txt_accountOrigen = new javax.swing.JTextField();
        btn_cuenta1 = new javax.swing.JButton();
        lbl_simboloOrign = new javax.swing.JLabel();
        txt_accountDestino = new javax.swing.JTextField();
        lbl_simboloDestiny = new javax.swing.JLabel();
        txt_idCuentaBancaria1 = new javax.swing.JTextField();
        txt_idCuentaBancaria2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cbox_tipoMoneda = new javax.swing.JComboBox<>();
        txt_idMoneda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TRANSACCIÓN");

        lbl_user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setText("Usuario");

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Realizar Operación");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevo)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cambio de Moneda"));

        jLabel2.setText("Tipo de Cambio :");

        jLabel8.setText("¿Cúanto tienes ? :");

        jLabel9.setText("Entonces recibes :");

        txt_origenCambio.setEnabled(false);

        txt_montoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_montoInicialActionPerformed(evt);
            }
        });
        txt_montoInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_montoInicialKeyPressed(evt);
            }
        });

        txt_montoFinal.setToolTipText("");
        txt_montoFinal.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_simboloOrigen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_simboloCambio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_simboloDestino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_montoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_montoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(txt_origenCambio)))
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lbl_simboloOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txt_montoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_simboloCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_montoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_simboloDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txt_origenCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Operación"));

        buttonGroup2.add(jRadioBtn_transferencia);
        jRadioBtn_transferencia.setText("TRANSFERENCIA");
        jRadioBtn_transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn_transferenciaActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioBtn_retiro);
        jRadioBtn_retiro.setSelected(true);
        jRadioBtn_retiro.setText("RETIRO");
        jRadioBtn_retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtn_retiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioBtn_retiro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioBtn_transferencia)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jRadioBtn_retiro)
                .addGap(27, 27, 27)
                .addComponent(jRadioBtn_transferencia)
                .addGap(23, 23, 23))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_dni.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_dni.setText("dni_usuario");

        lbl_IDTransaccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_IDTransaccion.setText("IdTransaccion");

        lbl_fechaHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_fechaHora.setText("FECHA Y HORA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_IDTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_fechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_IDTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_fechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Cuenta Bancaria"));

        txt_accountOrigen.setEnabled(false);

        btn_cuenta1.setText("buscar");
        btn_cuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cuenta1ActionPerformed(evt);
            }
        });

        txt_accountDestino.setEnabled(false);

        txt_idCuentaBancaria1.setEnabled(false);

        txt_idCuentaBancaria2.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_simboloOrign, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_idCuentaBancaria1)
                    .addComponent(txt_accountOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lbl_simboloDestiny, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_idCuentaBancaria2)
                            .addComponent(txt_accountDestino))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btn_cuenta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_idCuentaBancaria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idCuentaBancaria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_accountDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_simboloDestiny, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_simboloOrign, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_accountOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Elegir tipo de Cambio"));

        cbox_tipoMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Seleccionar >" }));
        cbox_tipoMoneda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_tipoMonedaActionPerformed(evt);
            }
        });

        txt_idMoneda.setEnabled(false);

        jLabel5.setText("IdMoneda");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbox_tipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_idMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_tipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_user, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cuenta1ActionPerformed
        CuentaBancariaController.callJDCuentaBancariaFromTransaccion(lbl_dni.getText(), lbl_user.getText());
    }//GEN-LAST:event_btn_cuenta1ActionPerformed

    private void jRadioBtn_transferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn_transferenciaActionPerformed

    }//GEN-LAST:event_jRadioBtn_transferenciaActionPerformed

    private void jRadioBtn_retiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtn_retiroActionPerformed

    }//GEN-LAST:event_jRadioBtn_retiroActionPerformed

    private void txt_montoInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_montoInicialKeyPressed
        

    }//GEN-LAST:event_txt_montoInicialKeyPressed

    private void txt_montoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_montoInicialActionPerformed
        double origenDolares, montoInicialSoles, montoFinalDolares;
        origenDolares = Double.parseDouble(txt_origenCambio.getText());
        montoInicialSoles = Double.parseDouble(txt_montoInicial.getText());
        montoFinalDolares = origenDolares * montoInicialSoles;
        BigDecimal resultado = new BigDecimal(montoFinalDolares).setScale(2, BigDecimal.ROUND_DOWN);
        txt_montoFinal.setText(String.valueOf(resultado));
//        txt_montoFinal.setText(String.valueOf(String.format("%.2f", montoFinalDolares)));
    }//GEN-LAST:event_txt_montoInicialActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jRadioBtn_retiro.isSelected()) {
            UsuarioDao usuarioDao = new UsuarioDaoImp();
            
            CuentaBancariaDao cuentaBancariaDao = new CuentaBancariaDaoImp();
            CuentaBancaria cuentaBancaria = new CuentaBancaria();
            
            Transaccion transaccion = new Transaccion();
            
            String idUsuario = usuarioDao.findUsuarioByDNI(lbl_dni.getText()).getIdUsuario();
            
            transaccion.setIdTransaccion(lbl_IDTransaccion.getText());
            transaccion.setIdUsuario(idUsuario);
            transaccion.setIdCuentaOrigen(txt_accountOrigen.getText());
            transaccion.setIdCuentaDestino(txt_accountDestino.getText());
            transaccion.setIdMoneda(txt_idMoneda.getText());
            transaccion.setMontoInicial(Double.parseDouble(txt_montoInicial.getText()));
            transaccion.setMontoFinal(Double.parseDouble(txt_montoFinal.getText()));
            transaccion.setFechaTransaccion(lbl_fechaHora.getText());
            TransaccionController.insertTransaccion(transaccion);
            
            double saldoActualCuentaBancaria = cuentaBancariaDao.find(txt_idCuentaBancaria1.getText()).getSaldo();
            double saldoFinalCuentaBancaria = saldoActualCuentaBancaria - Double.parseDouble(txt_montoInicial.getText());
            System.out.println("saldoFinalCuentaBancaria " + saldoFinalCuentaBancaria);
            cuentaBancaria.setIdCuentaBancaria(txt_idCuentaBancaria1.getText());
            cuentaBancaria.setSaldo(saldoFinalCuentaBancaria);
            cuentaBancariaDao.updateSaldo(cuentaBancaria);
            limpiar();
        } else if (jRadioBtn_transferencia.isSelected()) {
            UsuarioDao usuarioDao = new UsuarioDaoImp();
            
            CuentaBancariaDao cuentaBancariaDao = new CuentaBancariaDaoImp();
            CuentaBancaria cuentaBancaria = new CuentaBancaria();
            
            Transaccion transaccion = new Transaccion();
            
            String idUsuario = usuarioDao.findUsuarioByDNI(lbl_dni.getText()).getIdUsuario();
            
            transaccion.setIdTransaccion(lbl_IDTransaccion.getText());
            transaccion.setIdUsuario(idUsuario);
            transaccion.setIdCuentaOrigen(txt_accountOrigen.getText());
            transaccion.setIdCuentaDestino(txt_accountDestino.getText());
            transaccion.setIdMoneda(txt_idMoneda.getText());
            transaccion.setMontoInicial(Double.parseDouble(txt_montoInicial.getText()));
            transaccion.setMontoFinal(Double.parseDouble(txt_montoFinal.getText()));
            transaccion.setFechaTransaccion(lbl_fechaHora.getText());
            TransaccionController.insertTransaccion(transaccion);
            
            double saldoActualCuentaBancaria1 = cuentaBancariaDao.find(txt_idCuentaBancaria1.getText()).getSaldo();
            double saldoFinalCuentaBancaria1 = saldoActualCuentaBancaria1 - Double.parseDouble(txt_montoInicial.getText());
            
            cuentaBancaria.setIdCuentaBancaria(txt_idCuentaBancaria1.getText());
            cuentaBancaria.setSaldo(saldoFinalCuentaBancaria1);
            cuentaBancariaDao.updateSaldo(cuentaBancaria);
            
            double saldoActualCuentaBancaria2 = cuentaBancariaDao.find(txt_idCuentaBancaria1.getText()).getSaldo();
            double saldoFinalCuentaBancaria2 = saldoActualCuentaBancaria2 - Double.parseDouble(txt_montoFinal.getText());
            
            cuentaBancaria.setIdCuentaBancaria(txt_idCuentaBancaria2.getText());
            cuentaBancaria.setSaldo(saldoFinalCuentaBancaria2);
            cuentaBancariaDao.updateSaldo(cuentaBancaria);
            limpiar();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void cbox_tipoMonedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_tipoMonedaActionPerformed
        Moneda moneda = monedaDao.getMonedaByNombre(cbox_tipoMoneda.getSelectedItem().toString());
        txt_idMoneda.setText(moneda.getId());
        switch (cbox_tipoMoneda.getSelectedItem().toString()) {
            case "Dolar":
                txt_origenCambio.setText(String.valueOf(moneda.getTipoCambio()));
                lbl_simboloOrigen.setText(moneda.getSimbolo());
                lbl_simboloCambio.setText("S/.");
                lbl_simboloDestino.setText(moneda.getSimbolo());
                break;
            case "Soles":
                txt_origenCambio.setText(String.valueOf(moneda.getTipoCambio()));
                lbl_simboloOrigen.setText(moneda.getSimbolo());
                lbl_simboloCambio.setText("$.");
                lbl_simboloDestino.setText(moneda.getSimbolo());
                break;
            default:
                System.out.println("No se ha contemplado otro tipo de moneda");
                break;
        }
    }//GEN-LAST:event_cbox_tipoMonedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDTransaccion dialog = new JDTransaccion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cuenta1;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbox_tipoMoneda;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JRadioButton jRadioBtn_retiro;
    public javax.swing.JRadioButton jRadioBtn_transferencia;
    public javax.swing.JLabel lbl_IDTransaccion;
    public javax.swing.JLabel lbl_dni;
    private javax.swing.JLabel lbl_fechaHora;
    public javax.swing.JLabel lbl_simboloCambio;
    private javax.swing.JLabel lbl_simboloDestino;
    public javax.swing.JLabel lbl_simboloDestiny;
    private javax.swing.JLabel lbl_simboloOrigen;
    public javax.swing.JLabel lbl_simboloOrign;
    public javax.swing.JLabel lbl_user;
    public javax.swing.JTextField txt_accountDestino;
    public javax.swing.JTextField txt_accountOrigen;
    public javax.swing.JTextField txt_idCuentaBancaria1;
    public javax.swing.JTextField txt_idCuentaBancaria2;
    private javax.swing.JTextField txt_idMoneda;
    private javax.swing.JTextField txt_montoFinal;
    private javax.swing.JTextField txt_montoInicial;
    private javax.swing.JTextField txt_origenCambio;
    // End of variables declaration//GEN-END:variables
}
